### ISSUE TITLE
Hi can you help me to use IVF with 30 million vectors ?

### ISSUE THREAD

**Issue by shamanez** [matsui528/faiss_tips#1]
I am struggling with how to assign parameters for a ivf index, specially how to set the nlist and nprobe ? 

Also, what is the index_factory ?

**Comment by matsui528** [comment]
See the original paper of product quantization https://hal.inria.fr/inria-00514462v2/document
`nlist` and `nprobe` are k' and w in the paper, respectively.

If you are not familiar with faiss, I recommend setting `nlist` as \sqrt(N). In your case, `nlist` will be 5500. 

`nprobe` should be set to 1. That is the fastest but least accurate. If you want a more precise result, you can increase `nprobe`, such as 2, 4, 8, etc. It improves accuracy but makes the search slower.

`index_factory` is a helper function to instantiate an index class. See this https://github.com/facebookresearch/faiss/wiki/The-index-factory

**Comment by shamanez** [comment]
thanks a lot. :)

**Comment by shamanez** [comment]
@matsui528 

I have one more problem, I am also using faiss in a training process.  In this case, my dataset consists 7 million vectors. In every 500 steps, I update the vectors with a trained model. So I need to calculate the index again. In this process, add_index takes lots of time. I am using faisis with huggiface dataset library. 

```
    index = faiss.IndexHNSWFlat(index_hnsw_args.d, index_hnsw_args.m, faiss.METRIC_INNER_PRODUCT)
    dataset.add_faiss_index("embeddings", custom_index=index)
```

is there a different index that does faster add_faiss_index?

**Comment by matsui528** [comment]
See this https://github.com/facebookresearch/faiss/wiki/Faster-search

**Comment by shamanez** [comment]
thanks a lot it worked
