### ISSUE TITLE
Question about HNSW + IVFPQ

### ISSUE THREAD

**Issue by dohonghuan** [matsui528/faiss_tips#2]
Firstly, thank you for your faiss tips and survey (A Survey of Product Quantization).
I have questions about HNSW + IVFPQ.
1. We use IFVPQ to encode vector (reduce memory) and HNSW as Coarse-quantization (reduce search time) ?
2. If we search on Coarse-quantization (HNSW), why we set index.nprobe (belong to IFVPQ) as parameter instead of index.hnsw.efSearch (belong to HNSW) ?
Thank in advance.

**Comment by matsui528** [comment]
1. Yes
2. You can tweak efSearch as well. Some comments are:
    - IVFPQ is a framework, and HNSW is a component of it. When we try to construct a search system, it would be more beneficial to tweak the system's parameter (nprobe). For example, if we replace HNSW with another algorithm, we can compare the two using the same nprobe.
    - The nprobe is a very intuitive and easy-to-understand parameter with a fixed range. If nprobe is 1, the system is the fastest but less accurate. If nprobe is larger, it is slower but more accurate. So, it is easy to adjust. The other parameters, including efSearch, are not as intuitive.
    - If you look at the implementation of faiss, you will see that efSearch is fixed. This design is probably because the developers of faiss have tried many things and concluded that the value of efSearch should be fixed. Therefore, I followed the same idea and set only hnws_m as the parameter of HNSW.    https://github.com/facebookresearch/faiss/blob/a87930111eacad8eb22c68ea7d745e4f2f21a51b/faiss/impl/HNSW.cpp#L50
